Repository Veil-Project/veil, pull requests merged in 2019-05, with the labels that each got.

#511 [Qt] Show rescanning percentage on splash screen.
  src/qt/bitcoingui.cpp
  src/wallet/wallet.cpp
Labels: QA: Passed

#515 [Qt] Fixes cut off tool tip text across the application
  src/qt/forms/optionsdialog.ui
  src/qt/optionsdialog.cpp
  src/qt/res/css/main.css
  src/qt/veil.cpp
Labels: QA: Passed

#543 [GUI] Sync progress ui additions
  src/qt/bitcoingui.cpp
  src/qt/veil/forms/veilstatusbar.ui
  src/qt/veil/veilstatusbar.cpp
  src/qt/veil/veilstatusbar.h
Labels: QA: Passed, Tag: Needs Release Notes

#517 [Qt] Update pay amount text box
  src/qt/sendcoinsentry.cpp
Labels: QA: Passed

#528 [Miner] Filter out BIP30 enforced tx from new blocks.
  src/miner.cpp
Labels: Component: Miner

#516 [RPC] Add RPCConvertParam
  src/rpc/client.cpp
Labels: QA: Passed

#575 [Validation]Lock CheckZerocoinMint()
  src/consensus/tx_verify.cpp
Labels: Coin Type: Zerocoin, Tag: Syncing, Tag: Validation

#573 [Wallet] Add Transaction Size to Transaction Detail Dialog
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/veil/transactiondetaildialog.cpp
Labels: QA: Passed

#483 [Qt] Add warning label if zero coin balance is less than minimum.
  src/qt/veil/forms/settingsminting.ui
  src/qt/veil/settings/settingsminting.cpp
Labels: QA: Passed

#522 [RPC] Allow all address types in spendzerocoinmints
  src/chainparams.cpp
  src/wallet/rpczerocoin.cpp
Labels: QA: Passed, Tag: Needs Release Notes

#574 [RPC]Adding `getspendablebalance` RPC Call.
  src/wallet/rpcwallet.cpp
Labels: QA: Passed

#580 Remove bit 2 warning.
  src/chainparams.cpp
  src/validation.cpp
Labels: QA: Passed

#582 [GUI] Lock button focus & signal blocking fix.
  src/qt/veil/forms/veilstatusbar.ui
  src/qt/veil/veilstatusbar.cpp
Labels: QA: Passed

#583 [GUI] Extending clickable area of Staking & Precompute toggle switch.
  src/qt/res/css/main.css
  src/qt/veil/forms/veilstatusbar.ui
Labels: QA: Passed

#482 [Qt] Add mouse leave event to balance buttons.
  src/qt/veil/balance.cpp
  src/qt/veil/balance.h
  src/qt/veil/tooltipbalance.cpp
Labels: QA: Passed

#599 [GUI] Prefences tab - revert background to allow native OS styling
  src/qt/optionsdialog.cpp
Labels: QA: Passed
