Repository Veil-Project/veil, pull requests merged in 2019-06, with the labels that each got.

#579 [Wallet] searchdeterministiczerocoin progressbar
  src/veil/zerocoin/zwallet.cpp
  src/veil/zerocoin/zwallet.h
  src/wallet/rpczerocoin.cpp
Labels: QA: Passed

#588 [RPC] SpendZeroCoin Address Validation
  src/qt/sendcoinsentry.cpp
  src/wallet/rpczerocoin.cpp
Labels: QA: Passed

#485 [Qt] Add hyperlink for txid in transaction detail view.
  src/qt/veil/forms/transactiondetaildialog.ui
  src/qt/veil/transactiondetaildialog.cpp
  src/qt/veil/transactiondetaildialog.h
Labels: QA: Passed

#614 Reject < v4 zerocoin from mempool.
  src/validation.cpp
Labels: Priority: 3 - High

#620 [RPC] Fix rescanzerocoinwallet help message
  src/wallet/rpczerocoin.cpp
Labels: Code Review: Passed, QA: Passed

#623 [GUI] Status bar – Horizontally center the sync status button
  src/qt/veil/forms/veilstatusbar.ui
Labels: Code Review: Passed, QA: Passed
