Repository Veil-Project/veil, pull requests merged in 2019-11, with the labels that each got.

#683 [script][RPC] Properly parse and display zerocoin opcodes
  src/script/script.cpp
  src/script/script.h
Labels: Code Review: Passed, Component: RPC, QA: Passed

#666 [DOC] Corrected TravisCI badge, added release version and date badges
  README.md
Labels: Code Review: Passed, QA: Passed

#681 [GUI] Explicitly disable Dark Mode appearance on macOS
  share/qt/Info.plist.in
Labels: Code Review: Passed, QA: Passed, Tag: Waiting For Developer

#689 [QT] Correct "view in explorer" tooltip style
  src/qt/veil/forms/transactiondetaildialog.ui
  src/qt/veil/transactiondetaildialog.cpp
Labels: Component: GUI, Tag: Waiting For Code Review

#687 [Qt] Remove hide() on hideEvents
  src/qt/overviewpage.cpp
  src/qt/sendcoinsdialog.cpp
  src/qt/veil/addresseswidget.cpp
  src/qt/veil/addresseswidget.h
  src/qt/veil/receivewidget.cpp
  src/qt/veil/receivewidget.h
  src/qt/veil/settings/settingswidget.cpp
  src/qt/veil/settings/settingswidget.h
Labels: Tag: Waiting For QA

#664 [DOC] Updated gitian documentation to reference docker process
  doc/gitian-building/README.md
Labels: QA: Passed
