Repository Veil-Project/veil, pull requests merged in 2019-04, with the labels that each got.

#468 Add coin control updates to veil send dialog
  src/qt/coincontroldialog.cpp
  src/qt/coincontroldialog.h
  src/qt/forms/coincontroldialog.ui
  src/qt/forms/sendcoinsdialog.ui
  src/qt/forms/sendcoinsentry.ui
  src/qt/sendcoinsdialog.cpp
  src/qt/sendcoinsdialog.h
  src/qt/sendcoinsentry.cpp
Labels: Tag: Needs Release Notes

#427 Add Precomputing of Zerocoin Spends
  CMakeLists.txt
  src/Makefile.am
  src/init.cpp
  src/interfaces/wallet.cpp
  src/interfaces/wallet.h
  src/logging.cpp
  src/logging.h
  src/miner.h
  src/qt/veil/forms/veilstatusbar.ui
  src/qt/veil/mainwindow.cpp
  src/qt/veil/veilstatusbar.cpp
  src/qt/veil/veilstatusbar.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/rpc/client.cpp
  src/rpc/misc.cpp
  src/validation.cpp
  src/validation.h
  src/veil/proofofstake/stakeinput.cpp
  src/veil/proofofstake/stakeinput.h
  src/veil/zerocoin/accumulatormap.cpp
  src/veil/zerocoin/accumulatormap.h
  src/veil/zerocoin/accumulators.cpp
  src/veil/zerocoin/accumulators.h
  src/veil/zerocoin/lrucache.cpp
  src/veil/zerocoin/lrucache.h
  src/veil/zerocoin/precompute.cpp
  src/veil/zerocoin/precompute.h
  src/veil/zerocoin/witness.cpp
  src/veil/zerocoin/witness.h
  src/veil/zerocoin/ztracker.cpp
  src/veil/zerocoin/ztracker.h
  src/wallet/init.cpp
  src/wallet/rpczerocoin.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
Labels: Tag: Needs Release Notes

#487 Do not load corrupted duplicate block indexes.
  src/txdb.cpp
Labels: Tag: Needs Release Notes, Tag: Waiting For QA

#490 [Build] Update TravisCI Descriptors
  .travis.yml
  .travis/README.md
  .travis/lint_04_install.sh
  .travis/lint_05_before_script.sh
  .travis/lint_06_script.sh
  .travis/test_03_before_install.sh
  .travis/test_04_install.sh
  .travis/test_05_before_script.sh
  .travis/test_06_script_a.sh
  .travis/test_06_script_b.sh
  test/lint/lint-filenames.sh
Labels: Component: DevOps, Tag: Build System, Tag: TravisCI

#481 Add zerocoin to coincontrol
  src/interfaces/wallet.cpp
  src/interfaces/wallet.h
  src/qt/coincontroldialog.cpp
  src/qt/coincontroldialog.h
  src/qt/forms/coincontroldialog.ui
  src/qt/forms/sendcoinsdialog.ui
  src/qt/sendcoinsdialog.cpp
  src/qt/walletmodel.cpp
  src/wallet/coincontrol.cpp
  src/wallet/coincontrol.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Coin Type: Zerocoin, Component: GUI, Issue Type: Missing Functionality, Tag: Coin Control

#472 Connect GUI and RPC to wallet unlockforstaking only flag.
  CMakeLists.txt
  src/miner.cpp
  src/qt/res/css/main.css
  src/qt/veil/forms/veilstatusbar.ui
  src/qt/veil/settings/settingsminting.cpp
  src/qt/veil/veilstatusbar.cpp
  src/qt/veil/veilstatusbar.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/qt/walletview.cpp
  src/txdb.cpp
  src/veil/ringct/anonwallet.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/rpczerocoin.cpp
  src/wallet/wallet.cpp
Labels: Tag: Needs Release Notes

#480 [Qt] Change transaction listing to scale with DPI
  src/qt/overviewpage.cpp
Labels: Tag: Waiting For QA

#512 [Wallet]Fix change amount when minting zerocoin as change
  src/chainparams.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/veil/ringct/anonwallet.cpp
  src/wallet/wallet.cpp
Labels: Tag: Needs Release Notes

#513 [Wallet]Fix empty scriptpubkey causing issues creating CT transactions.
  src/veil/ringct/anonwallet.cpp
Labels: Tag: Needs Release Notes, Tag: Waiting For QA

#494 [Wallet][RPC] Add recoveraddresses rpc to regenerate keys and zerocoins after a seed import.
  src/rpc/client.cpp
  src/veil/ringct/anonwallet.cpp
  src/veil/ringct/anonwallet.h
  src/veil/ringct/anonwalletdb.cpp
  src/veil/ringct/anonwalletdb.h
  src/veil/ringct/stealth.cpp
  src/veil/zerocoin/zchain.cpp
  src/veil/zerocoin/zwallet.cpp
  src/veil/zerocoin/zwallet.h
  src/wallet/rpcwallet.cpp
  src/wallet/rpczerocoin.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Tag: Needs Release Notes

#530 [Build] Fix windows build with boost thread
  src/veil/zerocoin/zwallet.cpp
Labels: Component: DevOps, QA: Passed, Tag: Build System, Tag: TravisCI

#526 Add ringct and ct to automint
  src/veil/ringct/anonwallet.cpp
  src/veil/zerocoin/ztracker.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Tag: Needs Release Notes, Tag: Waiting For QA

#525 Fix mintable ringct and ct balances to show correcly
  src/veil/ringct/anonwallet.cpp
Labels: Tag: Needs Release Notes, Tag: Waiting For QA

#484 Make the push buttons in Advanced Preferences look more "clickable"
  src/qt/forms/optionsdialog.ui
Labels: QA: Passed
