Repository Veil-Project/veil, pull requests merged in 2019-12, with the labels that each got.

#632 [GUI] Adding new wallet lock/unlock tab to FAQ.
  src/Makefile.qt.include
  src/qt/locale/veil_en.ts
  src/qt/veil/forms/settingsfaq.ui
  src/qt/veil/forms/settingsfaq12.ui
  src/qt/veil/settings/settingsfaq.cpp
  src/qt/veil/settings/settingsfaq.h
  src/qt/veil/settings/settingsfaq12.cpp
  src/qt/veil/settings/settingsfaq12.h
  veil-qt.files
Labels: QA: Passed

#694 [Security] Update keys for publicly verifiable veil developers
  contrib/gitian-keys/README.md
  contrib/gitian-keys/keys.txt
Labels: Component: DevOps, QA: Passed

#677 [GUI] [Trivial] Changes primarily to written content style. Removal/updates of Zerocoin privacy mentions.
  src/qt/bitcoingui.cpp
  src/qt/locale/veil_en.ts
  src/qt/overviewpage.cpp
  src/qt/veil/forms/addresseswidget.ui
  src/qt/veil/forms/addressnewcontact.ui
  src/qt/veil/forms/balance.ui
  src/qt/veil/forms/createpassword.ui
  src/qt/veil/forms/mainwindow.ui
  src/qt/veil/forms/receivewidget.ui
  src/qt/veil/forms/sendconfirmation.ui
  src/qt/veil/forms/settingsadvance.ui
  src/qt/veil/forms/settingsadvanceinformation.ui
  src/qt/veil/forms/settingsbackup.ui
  src/qt/veil/forms/settingschangepassword.ui
  src/qt/veil/forms/settingsfaq.ui
  src/qt/veil/forms/settingsfaq01.ui
  src/qt/veil/forms/settingsfaq03.ui
  src/qt/veil/forms/settingsfaq04.ui
  src/qt/veil/forms/settingsfaq05.ui
  src/qt/veil/forms/settingsfaq06.ui
  src/qt/veil/forms/settingsfaq07.ui
  src/qt/veil/forms/settingsfaq08.ui
  src/qt/veil/forms/settingsfaq09.ui
  src/qt/veil/forms/settingsminting.ui
  src/qt/veil/forms/settingsmintingmanual.ui
  src/qt/veil/forms/settingswidget.ui
  src/qt/veil/forms/tooltipbalance.ui
  src/qt/veil/forms/transactiondetaildialog.ui
  src/qt/veil/forms/tutorialcreatewalletwidget.ui
  src/qt/veil/forms/unlockpassworddialog.ui
  src/qt/veil/forms/updateaddress.ui
  src/qt/veil/forms/veilstatusbar.ui
Labels: Code Review: Passed, Component: DevOps, Component: GUI, QA: Passed

#705 Update master branch to 1.0.4.99
  configure.ac
Labels: Code Review: Passed, Component: Core App

#703 [Network] Update seed nodes
  src/chainparams.cpp
Labels: Priority: 3 - High, QA: Passed, Tag: Syncing

#600 [GUI] Delete useless icons
  src/Makefile.qt.include
  src/qt/locale/veil_en.ts
  src/qt/res/icons/img-logo-binance.png
  src/qt/res/icons/img-logo-binance@2x.png
  src/qt/res/icons/img-logo-binance@3x.png
  src/qt/res/icons/img-logo-bittrex.png
  src/qt/res/icons/img-logo-bittrex@2x.png
  src/qt/res/icons/img-logo-bittrex@3x.png
  src/qt/res/icons/img-logo-coinbase.png
  src/qt/res/icons/img-logo-coinbase@2x.png
  src/qt/res/icons/img-logo-coinbase@3x.png
  src/qt/veil.qrc
  src/qt/veil/forms/settingsfaq02.ui
  src/qt/veil/settings/settingsfaq02.cpp
Labels: Component: GUI, QA: Passed

#712 [Build] Qt duplicate name warnings corrected
  src/qt/forms/overviewpage.ui
  src/qt/forms/sendcoinsdialog.ui
  src/qt/forms/sendcoinsentry.ui
  src/qt/veil/forms/sendconfirmation.ui
  src/qt/veil/forms/settingsadvanceinformation.ui
  src/qt/veil/forms/settingsadvancenetwork.ui
  src/qt/veil/forms/settingsfaq02.ui
  src/qt/veil/forms/settingsfaq03.ui
  src/qt/veil/forms/settingsminting.ui
Labels: Code Review: Passed, QA: Passed, Tag: Build System

#657 Fix formatting of ztracker remove pending
  src/veil/zerocoin/ztracker.cpp
  src/veil/zerocoin/ztracker.h
Labels: Code Review: Passed, QA: Passed
