Repository Veil-Project/veil, pull requests merged in 2019-09, with the labels that each got.

#630 [Wallet] Use one default stealth change address for CT/RingCT transactions.
  src/veil/ringct/anonwallet.cpp
  src/veil/ringct/anonwallet.h
  src/veil/ringct/rpcanonwallet.cpp
  src/wallet/wallet.cpp
Labels: Code Review: Passed, QA: Passed

#649 Add SECURITY.md to the project repo to outline the security reporting process
  SECURITY.md
Labels: Tag: Waiting For Code Review

#653 [Qt] Align text in the center of the progress bar.
  src/qt/bitcoingui.cpp
  src/qt/res/css/main.css
Labels: QA: Passed

#652 [QT] Fix address creation on Receive tab
  src/qt/veil/receivewidget.cpp
  src/qt/veil/receivewidget.h
Labels: Code Review: Passed, QA: Passed

#650 [RPC] Fix getblockstats to handle zerocoin spends, RingCT and PoS blocks
  src/rpc/blockchain.cpp
Labels: Code Review: Passed, QA: Passed
