Repository Veil-Project/veil, pull requests merged in 2020-01, with the labels that each got.

#644 [GUI] Updating & Simplifying Formatting/Styling of Content.
  src/qt/veil/forms/settingsfaq.ui
  src/qt/veil/forms/settingsfaq01.ui
  src/qt/veil/forms/settingsfaq02.ui
  src/qt/veil/forms/settingsfaq03.ui
  src/qt/veil/forms/settingsfaq04.ui
  src/qt/veil/forms/settingsfaq05.ui
  src/qt/veil/forms/settingsfaq06.ui
  src/qt/veil/forms/settingsfaq07.ui
  src/qt/veil/forms/settingsfaq08.ui
  src/qt/veil/forms/settingsfaq09.ui
  src/qt/veil/forms/settingsfaq10.ui
  src/qt/veil/forms/settingsfaq11.ui
  src/qt/veil/forms/unlockpassworddialog.ui
  src/qt/veil/settings/settingsfaq.cpp
  src/qt/veil/settings/settingsfaq01.cpp
  src/qt/veil/settings/settingsfaq04.cpp
  src/qt/veil/settings/settingsfaq05.cpp
  src/qt/veil/settings/settingsfaq06.cpp
  src/qt/veil/settings/settingsfaq07.cpp
  src/qt/veil/settings/settingsfaq08.cpp
  src/qt/veil/settings/settingsfaq09.cpp
  src/qt/veil/settings/settingsfaq10.cpp
  src/qt/veil/settings/settingsfaq11.cpp
Labels: Component: GUI, QA: Passed

#715 [Build] Fix automake's $VERSION var
  configure.ac
Labels: Code Review: Passed, QA: Passed, Tag: Build System

#720 Lint: initialization order issues.
  src/qt/modaloverlay.cpp
  src/qt/overviewpage.cpp
  src/qt/sendcoinsdialog.h
  src/qt/transactionrecord.h
  src/qt/veil/addressesmenu.cpp
  src/qt/veil/addresseswidget.cpp
  src/qt/veil/addressnewcontact.cpp
  src/qt/veil/addressreceive.cpp
  src/qt/veil/balance.cpp
  src/qt/veil/receivewidget.cpp
  src/qt/veil/settings/settingsminting.cpp
  src/qt/veil/settings/settingsrestore.cpp
  src/qt/veil/settings/settingsrestorefile.cpp
  src/qt/veil/settings/settingswidget.cpp
  src/qt/veil/tooltipbalance.cpp
  src/qt/veil/tutorialmnemonicrevealed.cpp
  src/qt/veil/updateaddress.cpp
  src/qt/veil/veilstatusbar.cpp
Labels: Code Review: Passed, QA: Passed, Tag: Build System

#721 Prevector: fix some compile errors. Make resize faster
  src/prevector.h
  src/serialize.h
  src/test/prevector_tests.cpp
Labels: Component: Core App, Tag: Waiting For Developer

#711 [Qt] AADPI fix - Enables high-DPI scaling in Qt on supported platforms
  src/qt/veil.cpp
Labels: Code Review: Passed, Component: GUI, Dev Status: Open PR, Tag: Build System, Tag: Waiting For QA

#733 include for CHAR_BIT.
  src/libzerocoin/bignum.h
Labels: Code Review: Passed, Priority: 3 - High, Tag: Build System

#726 [Net] Create devnet an alternative testnet
  contrib/veil-cli.bash-completion
  src/chainparams.cpp
  src/chainparamsbase.cpp
  src/chainparamsbase.h
  src/init.cpp
  src/net_processing.cpp
  src/qt/guiconstants.h
  src/qt/guiutil.cpp
  src/qt/locale/veil_en.ts
  src/qt/networkstyle.cpp
  src/qt/paymentserver.cpp
  src/qt/veil/transactiondetaildialog.cpp
  src/test/key_io_tests.cpp
  src/util.cpp
  src/util.h
  src/validation.cpp
  src/veil-cli.cpp
  src/veil-tx.cpp
  src/veild.cpp
  src/version.h
Labels: Component: Network, QA: Passed

#737 [Refactor] Rename Veil Labs to Veil Foundation
  src/miner.cpp
  src/test/monthly_rewards_tests.cpp
  src/validation.cpp
  src/veil/budget.cpp
  src/veil/budget.h
  src/wallet/wallet.cpp
Labels: Code Review: Passed

#713 [Qt][Build] Fix Mint Zerocoin amount
  src/qt/locale/veil_en.ts
  src/qt/veil/settings/settingsminting.cpp
Labels: Component: GUI, QA: Passed, Tag: Build System

#741 [Refactor] Don't include cpp files.
  src/qt/veil/addresseswidget.cpp
Labels: Code Review: Passed, QA: Passed

#728 [Performance] don't check ancestry if block is in the current chain
  src/validation.cpp
Labels: Component: Core App, QA: Passed

#698 [GUI] Removed faq tabs that weren't been used
  src/Makefile.qt.include
  src/qt/locale/veil_en.ts
  src/qt/veil/forms/settingsfaq02.ui
  src/qt/veil/forms/settingsfaq11.ui
  src/qt/veil/settings/settingsfaq.cpp
  src/qt/veil/settings/settingsfaq.h
  src/qt/veil/settings/settingsfaq02.cpp
  src/qt/veil/settings/settingsfaq02.h
  src/qt/veil/settings/settingsfaq11.cpp
  src/qt/veil/settings/settingsfaq11.h
Labels: Code Review: Passed, Component: GUI, QA: Passed

#730 GUI: Get rid of some deprecated calls.
  src/Makefile.qt.include
  src/qt/addresstablemodel.cpp
  src/qt/bantablemodel.cpp
  src/qt/bitcoinamountfield.cpp
  src/qt/bitcoingui.cpp
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/overviewpage.cpp
  src/qt/paymentserver.cpp
  src/qt/peertablemodel.cpp
  src/qt/recentrequeststablemodel.cpp
  src/qt/rpcconsole.cpp
  src/qt/splashscreen.cpp
  src/qt/splashscreen.h
  src/qt/splashscreenveil.cpp
  src/qt/transactiontablemodel.cpp
  src/qt/veil.cpp
Labels: Code Review: Passed, Component: GUI, QA: Passed

#743 [RPC] Fix sendrawtransaction Dandelion default
  src/rpc/rawtransaction.cpp
Labels: Code Review: Passed, Component: RPC, QA: Passed, Tag: Transaction Creation
