Repository Veil-Project/veil, pull requests merged in 2020-06, with the labels that each got.

#727 [Chain][Performance] Rework orphan pruning
  src/validation.cpp
Labels: Code Review: Passed, Component: Core App, Component: Wallet, QA: Passed, Tag: Chainstate

#757 [GUI] Fix coin control crashes
  src/qt/coincontroldialog.cpp
  src/qt/coincontroltreewidget.cpp
Labels: Code Review: Passed, Component: GUI, QA: Passed, Tag: Coin Control, Tag: Segfault

#769 script: fix SCRIPT_ERR_SIG_PUSHONLY error string
  src/script/script_error.cpp
Labels: Code Review: Passed, Priority: 1 - Low, QA: Passed

#774 [GUI] Do not use Qt's debugging information in the log handler.
  src/qt/veil.cpp
Labels: Code Review: Passed, Priority: 3 - High, QA: Passed, Tag: OS - OSX, Tag: Segfault

#796 Fix proof of stake veil data hash error
  src/chain.h
  src/primitives/block.cpp
  src/primitives/block.h
  src/rpc/blockchain.cpp
  src/validation.cpp
  src/veil/proofofstake/stakeinput.cpp
Labels: Code Review: Passed, Tag: Chainstate, Tag: PoW, Tag: Waiting For QA

#758 [ringct] Fix IsSpent check
  src/veil/ringct/anonwallet.cpp
Labels: Code Review: Passed, Coin Type: RingCT, Component: Core App, Component: Wallet, Tag: Transaction Creation

#792 Rework exceptions where reference is missing.
  src/qt/veil/settings/settingswidget.cpp
Labels: Code Review: Passed

#785 [ReIndex] Skip RingCT TX computation during resynching
  src/validation.cpp
Labels: Code Review: Passed, Coin Type: RingCT, Component: Core App, Priority: 3 - High, QA: Passed, Tag: Syncing

#786 gui: Fix leak in CoinControlDialog::updateView
  src/qt/coincontroldialog.cpp
Labels: Code Review: Passed, Component: GUI, Issue Type: Bug, Priority: 2 - Normal, QA: Passed

#788 Prevent UB when computing abs value for num opcode serialize
  src/script/script.h
Labels: Code Review: Passed
