Repository Veil-Project/veil, pull requests merged in 2021-06, with the labels that each got.

#780 init: remove boost from ThreadImport.
  src/init.cpp
  src/validation.cpp
  src/validation.h
Labels: Code Review: Passed, Priority: 1 - Low, QA: Passed

#904 [Wallet][RPC] Export basecoin transactions to CSV file
  CMakeLists.txt
  src/Makefile.am
  src/csv/CSV.hpp
  src/csv/CSVread.cpp
  src/csv/CSVwrite.cpp
  src/csv/License_GPLv3.txt
  src/csv/csv.h
  src/csv/libcsv.c
  src/csv/strerror.cpp
  src/csv/strerror.hpp
  src/utiltime.cpp
  src/utiltime.h
  src/wallet/rpcwallet.cpp
Labels: Code Review: Passed, Component: RPC, Component: Wallet, Tag: TransactionRecords

#951 [Consensus] Protect mapBlockIndex with its own mutex
  src/chain.h
  src/index/base.cpp
  src/init.cpp
  src/interfaces/wallet.cpp
  src/miner.cpp
  src/net_processing.cpp
  src/qt/coincontroldialog.cpp
  src/rest.cpp
  src/rpc/blockchain.cpp
  src/rpc/mining.cpp
  src/rpc/rawtransaction.cpp
  src/validation.cpp
  src/validation.h
  src/veil/ringct/anonwallet.cpp
  src/veil/zerocoin/accumulators.cpp
  src/veil/zerocoin/zchain.cpp
  src/veil/zerocoin/ztracker.cpp
  src/veil/zerocoin/zwallet.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
Labels: Code Review: Passed, Component: Consensus, Component: Core App

#955 arith: fix some constructor issues.
  src/libzerocoin/bignum.h
Labels: Tag: Waiting For Code Review, Tag: Waiting For QA

#940 Fix errors compiling for OSX catalina
  configure.ac
  depends/packages/boost.mk
  doc/build-osx.md
  src/qt/macdarkmode.mm
  src/qt/macdockiconhandler.mm
  src/qt/trafficgraphwidget.cpp
  src/qt/veil.cpp
Labels: Code Review: Passed, Tag: Build System, Tag: OS - OSX
