Repository Veil-Project/veil, pull requests merged in 2021-05, with the labels that each got.

#937 [Trivial] Add config include for building DEBUG_LOCKCONTENTION
  src/sync.cpp
Labels: Code Review: Passed, Tag: Build System

#915 [Mining][SHA256D] Reduce lock contention with SHA256D
  src/miner.cpp
Labels: Component: Core App, Component: Miner, Dev Status: In Progress, Tag: Waiting For Developer

#938 [Zerocoin][Validation] Cache checksum heights
  CMakeLists.txt
  src/Makefile.am
  src/veil/lru_cache.h
  src/veil/zerocoin/accumulators.cpp
Labels: Code Review: Passed, Coin Type: Zerocoin, Component: Consensus, Component: Miner

#939 [RPC][Trivial] Tweak exportzerocoins example to be sensible
  src/wallet/rpczerocoin.cpp
Labels: Coin Type: Zerocoin, Component: RPC, Tag: Waiting For Code Review

#944 [Consensus][RingCT] Add check for Duplicate Key Images
  configure.ac
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win.yml
  src/chainparams.cpp
  src/chainparams.h
  src/consensus/tx_verify.cpp
  src/consensus/validation.h
  src/logging.cpp
  src/logging.h
  src/net_processing.cpp
  src/validation.cpp
  src/veil/ringct/anon.cpp
  src/version.h
Labels: Coin Type: RingCT, Component: Consensus, Component: Wallet, Merging: Fork Required, Priority: 3 - High, Tag: Chainstate, Tag: Validation

#946 [GUI][Zerocoin] transaction list - handle receive from zerocoin transactions
  src/qt/transactionrecord.cpp
Labels: Code Review: Passed, Component: GUI, Tag: TransactionRecords

#906 [GUI] Move menu to cursor location instead of far right of the rectangle
  src/qt/veil/addressesmenu.cpp
  src/qt/veil/addressesmenu.h
  src/qt/veil/addresseswidget.cpp
Labels: Code Review: Passed, Component: GUI, Tag: TransactionRecords, Tag: Waiting For QA

#949 [Wallet] Lock cs_wallet in additional places.
  src/veil/ringct/anonwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Code Review: Passed, Component: Core App, Component: Wallet

#947 [Trivial] Placate clang warning string-plus-int
  src/chainparams.cpp
Labels: Tag: Build System, Tag: Waiting For QA

#950 [Consensus] Add locking on the chain index vector.
  src/chain.cpp
  src/chain.h
Labels: Code Review: Passed, Component: Consensus, Component: Core App, Tag: Waiting For QA

#948 [Utils] Templatify AssertLockHeld to placate clang warning
  src/sync.cpp
  src/sync.h
Labels: Code Review: Passed, Tag: Waiting For QA

#954 [Logging] Improve hash mismatch warning log message.
  src/txdb.cpp
Labels: Component: Consensus, Tag: Waiting For Code Review

#952 [Wallet][Consensus] Resolve misc clang lock annotation warnings.
  src/interfaces/wallet.cpp
  src/miner.cpp
  src/rpc/blockchain.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: Code Review: Passed, Component: Consensus, Component: Core App, Component: Wallet, Tag: Waiting For QA
