Repository Veil-Project/veil, pull requests merged in 2021-04, with the labels that each got.

#900 [GUI] Update wallet overview with coin and wallet information
  src/qt/forms/overviewpage.ui
Labels: Code Review: Passed, Component: GUI

#905 [GUI] Add missing resize Address_dot column
  src/qt/addressbookpage.cpp
Labels: Code Review: Passed, Component: GUI

#919 [Build] Fix OSX Github Action
  .github/workflows/build-factory.yml
Labels: Tag: Build System, Tag: CI, Tag: OS - OSX

#907 [GUI] Fix: Address Book menu hover background is white and text is white
  src/qt/addressbookpage.cpp
  src/qt/res/css/main.css
Labels: Component: GUI, Tag: Waiting For Code Review

#911 [RPC] Return mining addresses in listaddresses rpc command
  src/wallet/rpcwallet.cpp
Labels: Code Review: Passed, Component: RPC, Tag: Waiting For QA

#920 [Logging][Mining] Add BCLog::MINING category.
  src/logging.cpp
  src/logging.h
  src/miner.cpp
Labels: Code Review: Passed, Component: Core App, Component: Miner, Tag: Waiting For QA

#914 [Utils] Use gmtime_s with _WIN32
  src/utiltime.cpp
Labels: Code Review: Passed, Tag: Build System, Tag: OS - Windows

#921 [Mining] IncrementExtraNonce without cs_main
  src/miner.cpp
  src/miner.h
  src/rpc/mining.cpp
  src/test/test_veil.cpp
Labels: Code Review: Passed, Component: Core App, Component: Miner, QA: Passed

#928 [Logging] Define a STAKING log category.
  src/logging.cpp
  src/logging.h
  src/miner.cpp
  src/wallet/wallet.cpp
Labels: Code Review: Passed, Component: Miner, Tag: PoS

#908 [Wallet] If nautomintdenom is set, prioritize its use
  src/init.cpp
  src/qt/veil.cpp
  src/qt/veil/forms/settingsminting.ui
  src/qt/veil/settings/settingsminting.cpp
Labels: Tag: Automint, Tag: Needs Release Notes, Tag: Waiting For QA

#935 [Core] Properly shut down veild if init fails.
  src/veild.cpp
Labels: Code Review: Passed, Component: Core App

#923 [Mining] Use -miningaddress for in-wallet mining.
  src/init.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Code Review: Passed, Component: Miner

#924 [Staking][GUI] Unlock wallet for staking dialogue on click
  src/qt/veil/veilstatusbar.cpp
Labels: Code Review: Passed, Component: GUI, Tag: Encryption, Tag: PoS
