Repository Veil-Project/veil, pull requests merged in 2022-06, with the labels that each got.

#1008 [GUI] Set minimum scrollbar height for transactions history list
  src/qt/forms/overviewpage.ui
Labels: Component: GUI, QA: Passed, Code Review: Passed

#1004 [GUI] Show PoW type for coinbase transactions in transactions history
  src/interfaces/wallet.cpp
  src/interfaces/wallet.h
  src/qt/overviewpage.cpp
  src/qt/transactionfilterproxy.cpp
  src/qt/transactionfilterproxy.h
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/qt/transactiontablemodel.h
Labels: Component: GUI, Tag: TransactionRecords, QA: Passed, Code Review: Passed

#1001 Fix wrong CT / RingCT amounts in transaction history when wallet locked
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/overviewpage.cpp
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/qt/transactiontablemodel.h
  src/qt/walletview.cpp
  src/qt/walletview.h
  src/ui_interface.h
  src/veil/ringct/anonwallet.cpp
  src/veil/ringct/anonwallet.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Issue Type: Bug, Component: GUI, Tag: TransactionRecords, Coin Type: RingCT, Tag: StealthAddress, Coin Type: CT, Code Review: Passed

#766 Address segmentation faults in the Log message handlers on macOS.
  configure.ac
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/guiutil.cpp
  src/qt/macdockiconhandler.h
  src/qt/macdockiconhandler.mm
Labels: Tag: Segfault, Tag: OS - OSX, Tag: Build System, QA: In Progress, Tag: Waiting For Code Review

#993 Refactor ZC-specific staking functionality.
  src/veil/proofofstake/kernel.cpp
  src/veil/proofofstake/stakeinput.cpp
  src/veil/proofofstake/stakeinput.h
  src/wallet/wallet.cpp
Labels: Component: Wallet, Coin Type: Zerocoin, Tag: PoS, Tag: Waiting For Code Review
